#ifndef WIFI_STA_DEMO_H
#define WIFI_STA_DEMO_H

#define EXAMPLE_ESP_WIFI_SSID      "CONFIG_EXAMPLE_WIFI_SSID"
#define EXAMPLE_ESP_WIFI_PASS      "CONFIG_EXAMPLE_WIFI_PASSWORD"
#define EXAMPLE_ESP_MAXIMUM_RETRY  10

#endif 