/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.4.0
 *
 * Project: 'usart_demo.Debug+STM32F401RCTx' 
 * Target:  'Debug+STM32F401RCTx' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.8.1 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
