/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.4.0
 *
 * Project: 'f002a.Debug+PY32F002Ax5' 
 * Target:  'Debug+PY32F002Ax5' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "py32f0xx.h"



#endif /* RTE_COMPONENTS_H */
