#ifndef WIFI_STA_DEMO_H
#define WIFI_STA_DEMO_H

#define EXAMPLE_ESP_WIFI_SSID      "CONFIG_EXAMPLE_WIFI_SSID"
#define EXAMPLE_ESP_WIFI_PASS      "CONFIG_EXAMPLE_WIFI_PASSWORD"
#define EXAMPLE_ESP_MAXIMUM_RETRY  10

#define MAX_HTTP_RECV_BUFFER 512
#define MAX_HTTP_OUTPUT_BUFFER 2048
#define CONFIG_EXAMPLE_HTTP_ENDPOINT "192.168.0.123"
#define CONFIG_EXAMPLE_HTTP_PORT 5000

#define CONFIG_EXAMPLE_FIRMWARE_UPGRADE_URL "http://192.168.0.123:5000/update"

#endif 